### ISSUE TITLE
Error: An item with the same key has already been added.

### ISSUE THREAD

**Issue by Alfetta159** [stevehansen/csv#19] opened 2019-05-14 22:21 UTC
I can't see why I would get an error like this. My file has no key of any kind, so why would the assembly assume that it does. Is it assuming that the first column is some kind of unique key? It shouldn't assume anything.

**Comment by stevehansen** [comment] 2019-05-14 22:23
Probably duplicate of #18 ?
If the first row doesn't contain a header row you can specify that.

**Comment by Alfetta159** [comment] 2019-05-14 22:46
It's not obvious to infer that not having a header row is not default or would create an error from "An item with the same key has already been added."? Perhaps a better error message would help.

**Closed** 2019-05-15 05:55 UTC

**Comment by stevehansen** [comment] 2019-05-15 05:57
Should have done this sooner, the exception has been wrapped with a bit more information (https://github.com/stevehansen/csv/commit/6ee8d59695eb56a9dee27828fec5498e5cca5d94#diff-0afd2ee351abc786c74cb051a03ec329R103)

And the readme has been updated to add a mention that the HeaderPresent mode is the default and the different default options have been added to see what can be tweaked.
